### ISSUE TITLE
Minimum supported Gradle version is 7.0.2

### ISSUE THREAD

**Issue by wujianyin** [MRwangqi/pluginDemo#1]
依赖的Gradle版本有点高啊，很多项目依赖的Gradle版本还是5.x和6.x

**Comment by MRwangqi** [comment]
@wujianyin  emm，代码部分并没有用到 gradle 版本特性的 api，如果想用低版本的话，我觉得可以自己基于 5.x 和 6.x 的 gradle 版本创建个 gradle plugin 项目，然后将源码直接复制迁移过去
